runChecks: trueasdasdasdasd
allowOtherLabels: false
allowMultipleLabelsPerGroup: true
titlePattern: ".*"
extraMandatoryCheckListSections:
  - Context
extraMandatoryLabelGroups:
  - ["bug", "cosa"]
semanticTitle: true
